### ISSUE TITLE
application_plattform.register(), with BotoServerError

### ISSUE THREAD

**Issue by Dealers** [dreipol/django-scarface#2] opened 2015-01-12 08:41 UTC
Additional help is needed...
While this command is executed: application_plattform.register(), 
I am getting this error: 
Exception Type: BotoServerError
Exception Value:

BotoServerError: 400 Bad Request
{"Error":{"Code":"InvalidParameter","Message":"Invalid parameter: PlatformPrincipal not valid.","Type":"Sender"},"RequestId":"d027b359-0dd4-5296-9dd9-fe748596113c"}
Exception Location: C:\Python27\lib\site-packages\boto\sns\connection.py in _make_request, line 765

Any idea?
Thanks

**Comment by philipplaeubli** [comment] 2015-01-12 10:29
Several things could cause this:
- Did you specify SCARFACE_APNS_CERTIFICATE and SCARFACE_APNS_PRIVATE_KEY in your settings (also see the extract_keys command as documented: http://django-scarface.readthedocs.org/)
- When SCARFACE_APNS_MODE =  u"APNS_SANDBOX", is the certificate/private key from the sandbox enviromnent?

best wishes,
phil

**Comment by Dealers** [comment] 2015-01-12 10:47
Yes, i did all of these. Can it be something with boto?

‫ב-12 בינו׳ 2015, בשעה 12:29, ‏‏Philipp Läubli ‏notifications@github.com כתב/ה:‬

**Comment by philipplaeubli** [comment] 2015-01-12 10:56
Maybe the AWS Credentials (AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY) are invalid or do not have the permission to create an sns application or endpoint?

This example access-policy for your aws user should work:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "<SOME VALUE> ",
      "Effect": "Allow",
      "Action": [
        "sns:*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
```

Any luck with this?

**Comment by Dealers** [comment] 2015-01-12 11:14
No I already checked it...

‫ב-12 בינו׳ 2015, בשעה 12:56, ‏‏Philipp Läubli ‏notifications@github.com כתב/ה:‬

**Comment by philipplaeubli** [comment] 2015-01-12 16:31
Hmmm.. tried to reproduce the error and I only get that error when the SCARFACE_APNS_CERTIFICATE/SCARFACE_APNS_PRIVATE_KEY are not correctly set. For reference the settings must look like this:

![local_py_-_django-scarface_-____documents_repositories_django-scarface_](https://cloud.githubusercontent.com/assets/196704/5706394/def56182-9a80-11e4-9800-c1f37852ca49.png)

**Comment by Dealers** [comment] 2015-01-12 16:56
Thanks a lot. Sorry for my late response…
my variables looks similar except for the u”xxxx…”. (what this u”… “ for?)
also, I set the (SCARFACE_LOGGING_ENABLED = True), to “True” and you have “false”.

**Comment by philipplaeubli** [comment] 2015-01-12 17:05
The SCARFACE_LOGGING_ENABLED setting should not be the reason for your troubles. the u'xxx' this is just a way to declare a unicode string, see https://docs.python.org/2/howto/unicode.html and shouldn't be the problem either.
Are you working in the apns sandbox or using a production environment? Does the problem only occur with apns?

**Comment by philipplaeubli** [comment] 2015-01-12 17:06
and: have you tried to create the sns application directly in the AWS web console?

**Comment by Dealers** [comment] 2015-01-12 17:17
Yes and it is working. The only differences with your example is :

my variables looks similar except for the u”xxxx…”. (what this u”… “ for?)

also, I set the (SCARFACE_LOGGING_ENABLED = True), to “True” and you have “false”. 

Regards

Uzi Lumbroso

M +972-52-3330506

F  +972-9-7710184

uzi@dealers-app.com

Skype: uzport

Logo_(full).png 

 http://www.dealers-app.com www.dealers-app.com

The information contained in this document is proprietary of Dealers©. It contains confidential or privileged information, and is intended only for the use of the intended addressee thereof. If you are not the intended addressee, please be aware  that any use, disclosure, distribution and/or copying of this communication is strictly prohibited. If you receive this document or communication in error, please return it to Dealers© and delete it from your computer. Thank you. 

P Please consider the environment before printing this email

**Comment by Dealers** [comment] 2015-01-12 17:25
Yes, we are using the apns sandbox only right now so the problem only occur only with apns? If I use the Amazon SNS Dashboard it works OK with the same parameters.

**Comment by philipplaeubli** [comment] 2015-01-12 17:31
hmm... i can't really imagine any other solution at the moment. If you want you can email me your settings and i can try to reproduce the error (you may want to replace the aws user you are using and generate a new certificate). you can send me a mail to phil@dreipol.ch

**Comment by Dealers** [comment] 2015-01-12 17:47
Thanks Philipp. I will try few things and may send you my settings so you can try to reproduce

Regards

Uzi Lumbroso

M +972-52-3330506

F  +972-9-7710184

uzi@dealers-app.com

Skype: uzport

Logo_(full).png 

 http://www.dealers-app.com www.dealers-app.com

The information contained in this document is proprietary of Dealers©. It contains confidential or privileged information, and is intended only for the use of the intended addressee thereof. If you are not the intended addressee, please be aware  that any use, disclosure, distribution and/or copying of this communication is strictly prohibited. If you receive this document or communication in error, please return it to Dealers© and delete it from your computer. Thank you. 

P Please consider the environment before printing this email

**Comment by Dealers** [comment] 2015-01-13 03:41
Hi Philip 

I sent an email to  mailto:phil@dreipol.ch phil@dreipol.ch   With my setting info

Regards

Uzi

**Comment by melbic** [comment] 2015-09-24 13:53
I'll close this issue. If it isn't solved, please reopen.

**Closed as completed by melbic** 2015-09-24 13:53 UTC
